language: ruby
rvm:
- 2.1.4
deploy:
  provider: heroku
  api_key:
    secure: qXfQH1QxcCHfXvZJLyqkjITFu2AaROLqx1u58kFPGFnoE3VqG5xSnVYzykvyC6HaD0GqzddNftDkgoL3es6yRqK2S11SIkzPdH7AIavA+xApBM49Fv4XXhgtPstQBriOu2qlBXx10jf8PQ+1cIEBDvCM1CIVR0reB3AbTNNYSx5BN/DU56q2yQr186CTZghkuVtgHPrMVhxvpcVEemKGwJ8k8Dl58l5IlXPhS8AFzFu3iNpc52OLrmz8cWGIYRlc01PHx/lvUCxywd9lwlDnQyKMks55KfUf4YbKW5447BjlWLz8eecEbHX0f9jRVly0x6iQZF/Ik51VcTEZAdmjMLM4U1/IZhUGWEVRCcSdqkVPnMpKVXaoOlhTo7igr39JU3nom3cNP9kRzHNnc7jGY7QKTZZHE3HkwjeuXJGLH7dY9J+Z53q+gH6KCkIcJRpqQ+ADPkLPFKZMLSpgHy9cA/2bE3GIhWDm4cPGIPOUxiaY/HB2bBZJF71q5GotAuH8ZGg92BcwH3CiL6tlJA9zYGybBrIlPPoEI56zHmhK1K4tsObiBodIgvHeFgRMoJ3sfjIPdFkV46ZX9nsX0oUb+veHGblQjJxUYvRS3Rf+6GXLbay6CVJcWh2fCtdxszNQwNzULMKNNzlXcGZQqNurYfYx90fuAYV34YlCct4zSUg=
  app: tabarah-ranch-trakehners
  on:
    repo: sprestage/tabarah-ranch-trakehners
